# Paths to the data
path: /Users/saadbenboujina/Desktop/Projects/bachelor arbeit/TrainDataYolo
train: /Users/saadbenboujina/Desktop/Projects/bachelor arbeit/TrainDataYolo/0.7
val: /Users/saadbenboujina/Desktop/Projects/bachelor arbeit/TrainDataYolo/0.7
test: /Users/saadbenboujina/Desktop/Projects/bachelor arbeit/TrainDataYolo/val



nc: 1
# Main categories
names: ["boat"]

