# Paths to the data
path: /var/folders/3m/k2m2bg694w15lfb_1kz6blvh0000gn/T/wzQL.Cf1otW/Bachelorarbeit/Data
train: /var/folders/3m/k2m2bg694w15lfb_1kz6blvh0000gn/T/wzQL.Cf1otW/Bachelorarbeit/Data/Train
val: /var/folders/3m/k2m2bg694w15lfb_1kz6blvh0000gn/T/wzQL.Cf1otW/Bachelorarbeit/Data/Train

# Number of classes (categories)
nc: 69  # This number should reflect the total number of main categories.

# Main categories
categories:
  0: "Accommodation Vessels & Barges"
  1: "Aircraft Carriers"
  2: "Ancient Motor Vessels"
  3: "Auxiliaries"
  4: "Barge Carriers"
  5: "Barges"
  6: "Battleships"
  7: "Bulkers"
  8: "Buoy/Lighthouse Maintenance Vessels and Lightships"
  9: "Cable and Pipe Layers"
  10: "Casualties"
  11: "Cement Carriers"
  12: "Coast Guard"
  13: "Combined Carriers (OBO, CABU etc.)"
  14: "Construction Maintenance Vessels"
  15: "Containerships"
  16: "Corvettes"
  17: "Crane Ships"
  18: "Cruise Ships and Liners"
  19: "Cruisers"
  20: "Destroyers"
  21: "Dredgers"
  22: "Drill Ships"
  23: "Drilling Rigs"
  24: "Fast Attack Craft"
  25: "Ferries"
  26: "Fire Fighting Vessels"
  27: "Fishing Vessels"
  28: "Floating Production/Storage/Offloading Units"
  29: "Floating Sheerlegs and Crane Barges"
  30: "Formation and group photos"
  31: "Frigates"
  32: "Fruit Juice and Wine Tankers"
  33: "Gas Tankers"
  34: "General Cargo Ships"
  35: "Great Lakes Bulkers"
  36: "Great Lakes Tugs, Barges & Work Boats"
  37: "Guard Vessels/Safety/Rescue"
  38: "Harbour & tour boats / restaurant vessels"
  39: "Harbour Overview Images"
  40: "Heavy Lift Vessels and Heavy Load Carriers"
  41: "High Speed Vessels"
  42: "Historical / Unidentified Funnel Marks"
  43: "Hopper Barges"
  44: "Icebreakers"
  45: "Inland Dry Cargo Vessels"
  46: "Inland Passenger Vessels/Ferries"
  47: "Inland Special Purpose Vessels"
  48: "Inland Tankers"
  49: "Inland Tugs"
  50: "Inland Vessels"
  51: "Landing Ships"
  52: "Law Enforcement"
  53: "Lighthouse"
  54: "Live fish carriers"
  55: "Livestock Carriers"
  56: "Mine Warfare Ships"
  57: "Modern rig sailing ships / sailing yachts from 65 feet or 20 m LOA"
  58: "Motor Yachts from 65 feet or 20 m LOA"
  59: "Museum Ships"
  60: "Mystery Ships"
  61: "Offshore"
  62: "Ore Carriers"
  63: "Overview - fishing fleets"
  64: "Palletised Cargo Ships"
  65: "Passenger Vessels"
  66: "Patrol forces"
  67: "Pilot Vessels"
  68: "Platforms"

