# Paths to the data
path: /private/var/folders/3m/k2m2bg694w15lfb_1kz6blvh0000gn/T/wzQL.Cf1otW/Bachelorarbeit/ModelTraining

#/Users/saadbenboujina/Desktop/Projects/bachelor arbeit/TrainDataYolo
train: /private/var/folders/3m/k2m2bg694w15lfb_1kz6blvh0000gn/T/wzQL.Cf1otW/Bachelorarbeit/ModelTraining/data2
#/Users/saadbenboujina/Desktop/Projects/bachelor arbeit/TrainDataYolo/train
val: /private/var/folders/3m/k2m2bg694w15lfb_1kz6blvh0000gn/T/wzQL.Cf1otW/Bachelorarbeit/ModelTraining/val2

#/Users/saadbenboujina/Desktop/Projects/bachelor arbeit/TrainDataYolo/val

nc: 1
# Main categories
names: ["boat"]

