# Paths to the data
path: /Users/saadbenboujina/Downloads/seg.v9i.yolov8

#/Users/saadbenboujina/Desktop/Projects/bachelor arbeit/TrainDataYolo
train: /Users/saadbenboujina/Downloads/seg.v9i.yolov8/train
#/Users/saadbenboujina/Desktop/Projects/bachelor arbeit/TrainDataYolo/train
val: /Users/saadbenboujina/Downloads/seg.v9i.yolov8/valid

test: /Users/saadbenboujina/Downloads/seg.v9i.yolov8/valid

#/Users/saadbenboujina/Desktop/Projects/bachelor arbeit/TrainDataYolo/val

nc: 1
# Main categories
names: ["boat"]

