# Paths to the data
path: /Users/saadbenboujina/Downloads/seg.v9i.yolov8 (1)

train: /Users/saadbenboujina/Downloads/seg.v9i.yolov8 (1)/train
val: /Users/saadbenboujina/Downloads/seg.v9i.yolov8 (1)/valid


nc: 1
# Main categories
names: ["boat"]

